name: Deploy to IBM Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

      - name: Log in to IBM Cloud
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          ibmcloud login --apikey $IBM_CLOUD_API_KEY -r ${{ secrets.IBM_CLOUD_REGION }}

      - name: Set target resource group
        run: |
          ibmcloud target -g ${{ secrets.IBM_CLOUD_RESOURCE_GROUP }}

      - name: Build Docker image
        run: |
          docker build -t weather-dashboard-app .

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: |
          docker tag weather-dashboard-app ${{ secrets.DOCKER_HUB_USERNAME }}/weather-dashboard-app

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/weather-dashboard-app

      - name: Install IBM Cloud Code Engine plugin
        run: |
          ibmcloud plugin install code-engine -f

      - name: Select or create Code Engine project
        run: |
          ibmcloud ce project select --name weather-dashboard-project || \
          ibmcloud ce project create --name weather-dashboard-project

      - name: Create or update application
        run: |
          if ibmcloud ce application get --name weather-dashboard-app; then \
            ibmcloud ce application update --name weather-dashboard-app --image ${{ secrets.DOCKER_HUB_USERNAME }}/weather-dashboard-app; \
          else \
            ibmcloud ce application create --name weather-dashboard-app --image ${{ secrets.DOCKER_HUB_USERNAME }}/weather-dashboard-app --port 8080; \
          fi

      - name: Get application URL
        run: |
          ibmcloud ce application get --name weather-dashboard-app --output url
